START TRANSACTION;
ALTER TABLE "TeachingAssignments" ADD "GroupId" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_TeachingAssignments_GroupId" ON "TeachingAssignments" ("GroupId");

ALTER TABLE "TeachingAssignments" ADD CONSTRAINT "FK_TeachingAssignments_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260321193326_AddGroupIdToTeachingAssignmentsCombined', '10.0.5');

COMMIT;

START TRANSACTION;
DROP TABLE "Workloads";

ALTER TABLE "AspNetUsers" DROP COLUMN "Discriminator";

ALTER TABLE "AspNetUsers" DROP COLUMN "Role";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260404193236_RemoveUserRoleEnum', '10.0.5');

COMMIT;

START TRANSACTION;
DROP INDEX "IX_TeachingAssignments_TeacherId_SubjectId";

CREATE UNIQUE INDEX "IX_TeachingAssignments_TeacherId_SubjectId_GroupId" ON "TeachingAssignments" ("TeacherId", "SubjectId", "GroupId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260404194257_UpdateTeachingAssignmentUniqueConstraint', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TABLE "ScheduleNotes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ScheduleId" integer NOT NULL,
    "UserId" text NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ScheduleNotes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ScheduleNotes_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ScheduleNotes_Schedules_ScheduleId" FOREIGN KEY ("ScheduleId") REFERENCES "Schedules" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ScheduleNotes_ScheduleId" ON "ScheduleNotes" ("ScheduleId");

CREATE INDEX "IX_ScheduleNotes_UserId" ON "ScheduleNotes" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260419151832_AddScheduleNotes', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Schedules" ADD "IsOnline" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Schedules" ADD "MeetingLink" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260503201845_AddIsOnlineToSchedule', '10.0.5');

COMMIT;

