name: Deploy Planora-17 to Azure

on:
  push:
    branches:
      - Artur-17
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build and Publish
        # ОНОВЛЕНО: додано префікс Planora_2.0/ до шляху
        run: dotnet publish Planora_2.0/src/Planora.Web/Planora.Web.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Planora-17'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./publish